### ISSUE TITLE
Local dns stopped working, cannot ssh to it from main computer.

### ISSUE THREAD

**Issue by viliwonka** [KiraCore/testnet#10]
Running kira node privately on designated mini PC, it is convenient to `ssh` to it from main computer (windows), with computer name (local dns resolving). After installing kira and restarting PC, such feature does not work anymore, but I can still `ssh` to it with IP name.

**Comment by viliwonka** [comment]
I speculate but I think adding port 53 to Kira manager would help the issue, and can leave it disabled by default.

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
