### ISSUE TITLE
Sentry Restart Loop (testnet-2)

### ISSUE THREAD

**Issue by denisanix** [KiraCore/testnet#12]
After updating Public peers and restart sentry, it goes in endless restart loop, only way to fix it is run partial re init

**Comment by reb0rn21** [comment]
I have same issue, testnet-2 after update started to work fine some two hours later, but I did not update peer list sentry just goes at once at 0 and is stuck at restart, only private sentry is working but is slow and do not follow the blockchain

Then I made new server for just sentry it started to work and after 5min same public sentry go to 0 and start restarting, also i noticed 4 core VPS on sentry is loaded up to 15x on CPU not sure if that is issue, as validator is 5-8x load on same provider speck

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
