### ISSUE TITLE
Validator status inactive

### ISSUE THREAD

**Issue by SilasZhr** [KiraCore/testnet#13]
After upgrading to v0.2.1 and sending active command , I find that my validator status converted to inactive without few minutes. <br>
In order to solve this problem, I have tried to add seed node into list which worked for part of problem and my node is active for now. <br>
But the new challenge is that my rank is wiped  to 0 for some problem, I believe that I'm missing block all the time which is so weird.
BTW, I sincerely recommend that the team should build a discord room for validators.

**Comment by asmodat** [comment]
rank logic will be changed on testnet-3
