### ISSUE TITLE
Validator resource usage

### ISSUE THREAD

**Issue by Adorid** [KiraCore/testnet#15]
Validator is using too many resources, i want to mention more about  ssd usage as it has really high read/write
![hddusageaverage](https://user-images.githubusercontent.com/32141915/113740226-2ff4bc00-9709-11eb-94c1-3e3f6795040b.PNG)
![netusage](https://user-images.githubusercontent.com/32141915/113733167-e3a67d80-9702-11eb-9474-e2a39521bf8e.PNG)
![cpuusage](https://user-images.githubusercontent.com/32141915/113733185-e608d780-9702-11eb-91ec-f04ce11c0c55.PNG)

**Comment by asmodat** [comment]
should be resolved on branch `testnet-2`
