### ISSUE TITLE
catching up: false

### ISSUE THREAD

**Issue by hoanghiepluc** [KiraCore/testnet#18]
…
+ set +x
INFO: Minimum height: 85223, current height: 83497, catching up: false
INFO: Do NOT close your terminal, waiting for priv_sentry to finish catching up...
+ sleep 30

**Comment by NormanBB** [comment]
Update has been released.

Re-Initialize is needed.

**Comment by hoanghiepluc** [comment]
I've upgraded, it's still the same

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
