### ISSUE TITLE
Snapshot stuck

### ISSUE THREAD

**Issue by reb0rn21** [KiraCore/testnet#19]
Kira V0.2.2.3 Validator mode, snapshot got stuck at first manual run, restart does not help:
`+ SNAP_BLOCK=89651
++ isNaturalNumber 89651
+++ isNullOrEmpty 89651
+++ '[' -z 89651 ']'
+++ '[' 89651 == null ']'
+++ echo false
++ false
++ VTMP=false
+++ isInteger 89651
++++ isNullOrEmpty 89651
++++ '[' -z 89651 ']'
++++ '[' 89651 == null ']'
++++ echo false
+++ false
+++ VTMP=false
+++ [[ 89651 =~ ^-?[0-9]+$ ]]
+++ VTMP=true
+++ echo true
++ true
++ '[' 89651 -ge 0 ']'
++ VTMP=true
++ echo true
+ true
++ isNaturalNumber 89651
+++ isNullOrEmpty 89651
+++ '[' -z 89651 ']'
+++ '[' 89651 == null ']'
+++ echo false
++ false
++ VTMP=false
+++ isInteger 89651
++++ isNullOrEmpty 89651
++++ '[' -z 89651 ']'
++++ '[' 89651 == null ']'
++++ echo false
+++ false
+++ VTMP=false
+++ [[ 89651 =~ ^-?[0-9]+$ ]]
+++ VTMP=true
+++ echo true
++ true
++ '[' 89651 -ge 0 ']'
++ VTMP=true
++ echo true
+ true
+ '[' 89651 -lt 89651 ']'
+ echo 'INFO: Latest Block Height: 89651'
INFO: Latest Block Height: 89651
+ '[' false == true ']'
+ '[' 89651 -gt 0 ']'
+ echo 'INFO: Updating progress bar...'
INFO: Updating progress bar...
+ '[' 89651 -lt 109342 ']'
++ bc
++ echo 'scale=2; ( ( 100 * 89651 ) / 109342 )'
+ PERCENTAGE=81.99
+ '[' 89651 -ge 109342 ']'
+ echo 81.99
+ ps -p 48
+ echo 'INFO: Waiting for snapshot node to sync  89651/...'
INFO: Waiting for snapshot node to sync  89651/...
+ sleep 30
+ '[' 89651 -gt 89651 ']'
+ echo 'WARNING: Block did not changed! (89651)'
WARNING: Block did not changed! (89651)
+ '[' 89651 -lt 109342 ']'
+ '[' 0 -ge 4 ']'
+ '[' -z 48 ']'
+ i=1
+ echo 'INFO: Waiting for block update test 1/4'
INFO: Waiting for block update test 1/4
+ :
+ echo 'INFO: Checking node status...'
INFO: Checking node status...
++ sekaid status
++ jq -rc .
+ SNAP_STATUS='{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"c25bf455046807ac6aaa9555c1d5ea4598dcfc1f","listen_addr":"tcp://0.0.0.0:26656","network":"testnet-2","version":"","channels":"402021222330386061","moniker":"KIRA SNAPSHOT NODE","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:26657"}},"SyncInfo":{"latest_block_hash":"248DD5F5889F30321E174E9E01475AE2549D4BE3A4EB43A526E137048BCD6A1B","latest_app_hash":"21E2B73A3CA45C2E7B742E71F675703AA43CBCDFF72C91F565C39C52F544A7F1","latest_block_height":"89651","latest_block_time":"2021-04-08T07:43:03.385546127Z","earliest_block_hash":"F43DB96CF71EFD830CB6EEFB86A66832A20FDD41B8D62254C0163CC2EDE36980","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2021-04-03T03:54:14.832180699Z","catching_up":true},"ValidatorInfo":{"Address":"A64378251ED1702C14959FA4BBFDA50715A22503","PubKey":{"type":"tendermint/PubKeyEd25519","value":"eLVoZ/C2o1u+ebR5LGNMs4JwQsAIwPHMY5OGJo8P9os="},"VotingPower":"0"}}'
++ echo '{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"c25bf455046807ac6aaa9555c1d5ea4598dcfc1f","listen_addr":"tcp://0.0.0.0:26656","network":"testnet-2","version":"","channels":"402021222330386061","moniker":"KIRA' SNAPSHOT 'NODE","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:26657"}},"SyncInfo":{"latest_block_hash":"248DD5F5889F30321E174E9E01475AE2549D4BE3A4EB43A526E137048BCD6A1B","latest_app_hash":"21E2B73A3CA45C2E7B742E71F675703AA43CBCDFF72C91F565C39C52F544A7F1","latest_block_height":"89651","latest_block_time":"2021-04-08T07:43:03.385546127Z","earliest_block_hash":"F43DB96CF71EFD830CB6EEFB86A66832A20FDD41B8D62254C0163CC2EDE36980","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2021-04-03T03:54:14.832180699Z","catching_up":true},"ValidatorInfo":{"Address":"A64378251ED1702C14959FA4BBFDA50715A22503","PubKey":{"type":"tendermint/PubKeyEd25519","value":"eLVoZ/C2o1u+ebR5LGNMs4JwQsAIwPHMY5OGJo8P9os="},"VotingPower":"0"}}'
++ jq -rc .SyncInfo.latest_block_height
+ SNAP_BLOCK=89651
++ isNaturalNumber 89651
+++ isNullOrEmpty 89651
`

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
