### ISSUE TITLE
Unhealthy infrastructure

### ISSUE THREAD

**Issue by MartinGalee** [KiraCore/testnet#2]
Infrastructure is unhealthy for several hours. Restart of testnet might be necessary. All containers except snapshot are unhealthy. Same issues reported also by other users.

**Comment by greenestcoin** [comment]
I have the same problem

**Comment by onemedicine** [comment]
Have the same problem， on Ubuntu 20.04.1 LTS

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
