### ISSUE TITLE
I want to be a validator

### ISSUE THREAD

**Issue by sandhao** [KiraCore/testnet#20]
I have not been able to become a validator. I have sent several unjuil requests, but it still doesn’t work. I don’t know why, it’s always
“block...
Waiting for '' to be included in the 
”
my Val.ADDR:
kira17h059f66q0mthdp5xhcfjea5fttmluejgkaxe7

**Comment by asmodat** [comment]
Public Testnet Announcement: https://medium.com/kira-core/kira-launches-public-testnet-df5bcad028b8

1. [Read Milestone 1 Documentation](https://medium.com/kira-core/kira-testnet-phase-0-milestone-1-f667b1522b31)
2. [Read Milestone 2 Documentation](https://medium.com/kira-core/kira-testnet-phase-0-milestone-2-fc9f56b262ea)
3. [Visit testnet repository](https://github.com/KiraCore/testnet/blob/main/README.md) to find instructions how to join Public Testnet

contact support.kira.network in case of any issues
