### ISSUE TITLE
[BUG]. Kira network manager

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#22]
After adding seeds manually:

![2021-04-18_00-10](https://user-images.githubusercontent.com/70693118/115126798-82bc5680-9fda-11eb-9b18-89296dedaf78.png)

https://github.com/KiraCore/kira/blob/d91f4d024c7844bb31cdb4cc8cb3b04c188747e4/workstation/kira/kira-networking.sh

COMMON_PATH="$DOCKER_COMMON/$DOCKER_COMMON"

suggest that it should be like:
COMMON_PATH="$DOCKER_COMMON"
      
echoInfo "INFO: Copying $TYPE configuration to the $CONTAINER container common directory..."
cp -a -v -f "$FILE" "$COMMON_PATH/$TYPE"

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
