### ISSUE TITLE
autodiscovering snapshots

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/testnet#23]
The autodiscovery works and it will search for a peer with a snapshot.
Except, it finds a peer with a very very old snapshot and proceeds without question.

Feature request / suggestion , ability to skip a found snapshot if it's too old or not recent enough.

![image](https://user-images.githubusercontent.com/6506666/115141178-3c4b1400-a03b-11eb-9c60-4cd6086f3d2f.png)

**Comment by asmodat** [comment]
you can use advanced node or connect to node that exposes snapshot, auto discovery only exists if your node does not expose one
