### ISSUE TITLE
Stop all containers doesnt seem to work

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/testnet#24]
When choosing Stop all containers it seems to run through the process but containers begin to start automatically again.

![image](https://user-images.githubusercontent.com/6506666/115148834-ab3b6380-a061-11eb-857c-142c046de346.png)

Stop process log:
https://justpaste.it/6n7nl

RIght after pressing any key back to the Kira Manager I can see the containers starting already:

![image](https://user-images.githubusercontent.com/6506666/115149079-ba6ee100-a062-11eb-9f56-329c527985ac.png)

**Comment by asmodat** [comment]
Thank you, hotfix was added to branch `testnet`
