### ISSUE TITLE
After exhausting attempts to initialize validator - setup failed

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#26]
![validator_init](https://user-images.githubusercontent.com/70693118/115226694-3840f400-a118-11eb-820e-132a53a4d589.png)

After exhausting attempts to initialize the validator variable NODE_ID value is Empty.

This leads to a crash of installation.

![Fail](https://user-images.githubusercontent.com/70693118/115227153-c61cdf00-a118-11eb-88df-2bd38b2c32a7.png)

**Comment by denisanix** [comment]
Have the same issue

**Comment by MrLutik** [comment]
will check in testnet-3
