### ISSUE TITLE
Genesis file download failure

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#27]
Advanced setup.

Attempting download genesis file: https://github.com/KiraCore/testnet/blob/main/testnet-2/genesis.json
At first place downloading goes ok. 
![genesis_add](https://user-images.githubusercontent.com/70693118/115229520-d1bdd500-a11b-11eb-8b57-f903762ee73d.png)

After successful download script failed to recognize success. And starting the second attempt:

![shrinked_genesis](https://user-images.githubusercontent.com/70693118/115229883-4133c480-a11c-11eb-8171-c72d6b4ed821.png)

But this time wget receives sliced address and as a result 404 Error

**Comment by asmodat** [comment]
Use raw file you are downloading a HTTP page otherwise.

https://raw.githubusercontent.com/KiraCore/testnet/main/testnet-2/genesis.json
