### ISSUE TITLE
Installation problems (not resolved to end testnet)

### ISSUE THREAD

**Issue by Ttk69** [KiraCore/testnet#35]
hi. my kira adress kira1rauchfdp5dcqp4j3gywhezt2wpy7hua6a9lkcv i'm in validators list. server's ip adress 75.119.154.212.
hardware: 4 cores amd epyc 7000, 8 gb ram, 100 gb ssd. Ubuntu 20.04

1. after first installation my node hadn't receive'd status "waiting". i hade tried to use faucet (not helped for me). try'd to stop containers (not helped). try'd to send transaction to join validators set (sekaid tx customstaking claim-validator-seat). and it didn't help.

2.after this i made reinitialize. but process stopped with this issue:

Successfully tagged base-image: latest
+ docker image ls
REPOSITORY TAG IMAGE ID CREATED SIZE
base-image latest de6fb5aae7b2 1 second ago 4.09GB
ubuntu 20.04 26b77e58432b 6 days ago 72.9MB
registry 2.7.1 ee34aa9d8ab2 8 days ago 26.2MB
+ docker tag base-image: latest registry.regnet.local: 5000 / base-image
+ docker push registry.regnet.local: 5000 / base-image
The push refers to repository [registry.regnet.local: 5000 / base-image]
Get http: //registry.regnet.local: 5000 / v2 /: dial tcp 10.1.0.2:5000: connect: no route to host

i've found solution in kira testers tg - https://github.com/KiraCore/kira/edit/master/workstation/setup/registry.sh

3.after installation my node got status - consensus halted. and the status did not change whatever I did (restarting blocks, restarting server, sending "sekaid tx customstaking claim-validator-seat").

4.in kira testers tg i got advice to make clean installation - and that's all. i can not install kira node for 4 day's (6 reinitialisations) i got different errors while installation:

- ERROR: Node failed or status could not be fetched (1/3), your netwok connectivity might have been interrupted

- WARNING: sentry is not initialized yet (and installation stops in sentry getting blocks)

i had tried to use different ip of public nodes. but it didn't help. ip list 3.11.224.235, 68.183.113.128, 52.56.117.134

and after this i founded that testnet-2 is over. but i didn't install fine works node

**Comment by asmodat** [comment]
Resolved with v0.3.2.3 - `testnet-3`
