### ISSUE TITLE
[BUG] Testnet-3 Kirascan wasn't able to find IP address

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#41]
[system-cleanup-1-v0.3.0.0.log](https://github.com/KiraCore/testnet/files/6414083/system-cleanup-1-v0.3.0.0.log)

![image](https://user-images.githubusercontent.com/70693118/116862407-5e34c100-ac0d-11eb-96a4-8a491aa75e23.png)

data from journalctl -u kirascan -o cat

![image](https://user-images.githubusercontent.com/70693118/116862628-b8ce1d00-ac0d-11eb-88f6-7662e319f5c3.png)

seems it is connected to next screen. Docker interfaces are still up.

![image](https://user-images.githubusercontent.com/70693118/116867307-8d4f3080-ac15-11eb-81af-da7cc6bd1135.png)

**Comment by MrLutik** [comment]
SOLVED. While kirascan wasn't able to find IP i did next:
1. touch /docker/shared/common_ro/local_ip 
2. touch /docker/shared/common_ro/public_ip
3. echo 'my IP addr' >> local_ip && echo 'my IP addr' >> public_ip

**Comment by asmodat** [comment]
Resolved with v0.3.2.3 - `testnet-3`
