### ISSUE TITLE
[BUG] Testnet-3 Kira manager stuck on loading infrustructure

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#43]
![image](https://user-images.githubusercontent.com/70693118/116906124-87bf0e00-ac48-11eb-98fa-88ce016b8e5b.png)

If the manager stuck like that - you need to check kirascan.service
1. Logging as a root. service --status-all check if kirascan running. if not follow next step
2. rm -rf /home/kira1/kirascan /home/kira1/kirascan/status /home/kira1/kirascan/logs /home/kira1/snap/status /home/kira1/dump/kirascan (kirascan.service will fail to start if this directories already present)
3. systemctl start kirascan.service
4. now we should check it systemctl status kirascan.service if it is active FINALLY:
5. kira

**Comment by asmodat** [comment]
Resolved with v0.3.2.3 - `testnet-3`
