### ISSUE TITLE
Testnet - 3 stuck on sentry syncing

### ISSUE THREAD

**Issue by DenysOf** [KiraCore/testnet#44]
After a few attempts and different peers used, sentry still stuck

<img width="849" alt="Screenshot 2021-05-04 at 10 47 13" src="https://user-images.githubusercontent.com/77796082/116986753-1756d200-acc6-11eb-8396-337900a9b67e.png">
[kira.zip](https://github.com/KiraCore/testnet/files/6420239/kira.zip)

**Comment by asmodat** [comment]
Resolved with v0.3.2.3 - `testnet-3`
