### ISSUE TITLE
[Bug] Testnet-3 api/metada can't obtain data from block hash only from block high

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#46]
I have tried with double quotes as well
![image](https://user-images.githubusercontent.com/70693118/117109605-96630d80-ad8d-11eb-9226-d2ca740f3ed7.png)

![image](https://user-images.githubusercontent.com/70693118/117109751-cf9b7d80-ad8d-11eb-9874-b7fe28b5c0e0.png)

![image](https://user-images.githubusercontent.com/70693118/117109793-dde99980-ad8d-11eb-8028-3d5eb2765cb1.png)

**Comment by asmodat** [comment]
Would need more details in this issue
