### ISSUE TITLE
[PERFOMANCE] Missed block qty improvement

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#47]
I made a script to get avg ping among all network actors. 
To have a good peers is a good start to imporve your node perfomance. #my personal opinion

sudo apt update
sudo apt install git
cd /${HOME} #enter home directory
mkdir - p tmp #creating tmp directory if not exist
cd tmp/ #entering tmp dir
git clone https://github.com/MrLutik/KiraScan.git #getting script
cd KiraScan #entering dir
python3 kirascan.py #starting a script

it takes a while to process.
![image](https://user-images.githubusercontent.com/70693118/117529919-19c96c80-afe3-11eb-82b5-35acda418507.png)

after processing through all peers you will get a result(comma separated list of IPs) with a best 20 peers by avg ping.

![image](https://user-images.githubusercontent.com/70693118/117530956-b5a9a700-afe8-11eb-8c5b-4f8bbde6292c.png)

after that i went here:
![image](https://user-images.githubusercontent.com/70693118/117531004-f0134400-afe8-11eb-861f-6f6e779be075.png)

than to private peers:
![image](https://user-images.githubusercontent.com/70693118/117531019-07523180-afe9-11eb-9b19-60e3db5f6366.png)
pressed V
![image](https://user-images.githubusercontent.com/70693118/117531036-1933d480-afe9-11eb-988e-5986b7302ed1.png)

than copypast peers ip 
![image](https://user-images.githubusercontent.com/70693118/117531107-93fcef80-afe9-11eb-9553-f4f624a4dc8f.png)

after that many times Y you have to push

Than S for save changes and R for restart oriv_sentry

it will take couple mins.

P.S. This is my steps only. NOT AN INSTRUCTION OR RECOMENDATION.
IT IS NOT APPROVED BY ADMINS as well. SO IT IS UP TO YOU TO PROCEED OR NOT.

Formula to check perfomance:
(1 - STREAK/BLOCK_HEIGHT)*100% = RES - is a % of missed block

**Comment by asmodat** [comment]
good suggestion, will be used in seeding nodes in automated setup (selection of nodes by ping response)
