### ISSUE TITLE
v0.3.2.3 Update report

### ISSUE THREAD

**Issue by KathleeniSmithz45** [KiraCore/testnet#49]
I can't install update v0.3.2.3 Update successfully. I stuck in picture below for a long hours. Even if I tried to reinstall, still stucked for a long time.

![image](https://i.ibb.co/zPYSBq8/1.png)
https://ibb.co/8Ppjf1z

**Comment by NormanBB** [comment]
I suggest you summit a full log.

Use dump all logs and attach the kira.zip.

**Comment by KathleeniSmithz45** [comment]
[kira.zip](https://github.com/KiraCore/testnet/files/6447750/kira.zip)
