### ISSUE TITLE
Follow up on issue 4 - Finding out why the chain stopped

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/testnet#5]
Most validators that posted the error show this before the chained stopped:

`[0m"commit failed for application: error changing validator set: duplicate entry Validator{EBAA8A1AA4EC636AE3345436C291B51977B06D5B PubKeyEd25519{6DDCB539FEC02B209DC7FAB0F2670CF3FEA7564BE58181A495013D5BB6B7427B} VP:1 A:0} in`

The list was already filled with this validator:
![image](https://user-images.githubusercontent.com/6506666/113444554-67572600-93f4-11eb-9ea2-5fc434e569f2.png)

Checking the address is showing:
![image](https://user-images.githubusercontent.com/6506666/113444726-bc933780-93f4-11eb-8165-1d949a817fd7.png)

(adding this issue to get a form submit with the findings)

**Comment by Creamers158** [comment]
Though the transactions make by that address where at complete different blocks:

228F31D3667DF81485F8E3CADCA6FC65CD0613CF1E79F7C2C5188053203211D3  @  40091

D5502A635511B498F2536642A67069B0BBB63FDC89B0D20E99780962323B5B75  @  40094

8E161E3FD4BEB38118C24D9BF81633DD5FDE48ADD17F6AC3A4ACB182C83514A6   @  40119

BD723DA33CE2352EBCB597EB0C82387F70D8C67734C3002C3842945C3A165497  @   49875

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
