### ISSUE TITLE
[BUG] Testnet-3 v0.3.2.3 REGISTRY container constant failure

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#51]
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "bash": executable file not found in $PATH: unknown

After some hours of stable work KM starts to be inactive.

Restart of the container doesn't help.

![image](https://user-images.githubusercontent.com/70693118/117617871-d0f5ed00-b175-11eb-9561-d8b1e4ec9db5.png)

**Comment by asmodat** [comment]
resolved with v0.3.2.5
