### ISSUE TITLE
 v0.3.2.3 Validator becomes inactive / CONSENSUS HALTED

### ISSUE THREAD

**Issue by DenysOf** [KiraCore/testnet#52]
Restart of containers is not help, see logs attached. 

[kira.zip](https://github.com/KiraCore/testnet/files/6454737/kira.zip)

**Comment by DenysOf** [comment]
<img width="650" alt="Screenshot 2021-05-10 at 21 13 35" src="https://user-images.githubusercontent.com/77796082/117719613-8310d180-b1d5-11eb-8aed-15a88fd9fd14.png">

**Comment by asmodat** [comment]
Sould be resolved with v0.3.7.7
