### ISSUE TITLE
[BUG] Testnet-3 0.3.2.5 catching up failure 

### ISSUE THREAD

**Issue by MrLutik** [KiraCore/testnet#53]
![image](https://user-images.githubusercontent.com/70693118/117958361-9a5dd500-b323-11eb-8085-27f5c8a5b32c.png)

![image](https://user-images.githubusercontent.com/70693118/117958381-a053b600-b323-11eb-9fe1-fad98256f408.png)

![image](https://user-images.githubusercontent.com/70693118/117959187-6df68880-b324-11eb-80c0-3bb83c56b112.png)

**Comment by asmodat** [comment]
Sould be resolved with v0.3.7.7
