### ISSUE TITLE
Follow up on issue 4 - claimseat bug network halt

### ISSUE THREAD

**Issue by daluxxx** [KiraCore/testnet#7]
Hey all, 

I am the operator of StakesStone and as already mentioned by Creamers158 in issue 4, for me it was possible to claim more than one seat as a validator in the network with the same public key. This also led to several errors in the logs of other validators. For me, the first time I issued the command "sekaid tx customstaking claim-validator-seat" I got an RPC error. Afterwards, I re-submitted the command and the tx got successfully through. I again submitted the tx, and it again got through. I thought that there would be an error handling or a check to cross-check if the before submitted public key is already in the validator list, however, as seen now in issue 4 my validator was submitted twice in the validator list.

After submitting the claim-validator-seat, my validator ran fine and I also made blocks. I checked one day after claiming the seat and my validator ended up missing blocks. If this is related to the network halt, currently I am not yet sure. But I think there should be a cross-check if a validator is already in the set, or not.

**Comment by daluxxx** [comment]
After my validator stopped signing, I also got the error "Consensus halted" and an unhealthy frontend and validator flag.

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
