### ISSUE TITLE
No discovering of peers on public sentry

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/testnet#9]
I've been running testnet-1 without missing any blocks, pretty long streak, but now on testnet-2 I kept missing blocks.

I investigated and saw that the sentry only had two peers:

![image](https://user-images.githubusercontent.com/6506666/113482121-6b8b4e00-949d-11eb-8040-b87cb8c12915.png)

After setting some seeds and peers using the kira network manager and restarting the container it suddenly increased to +/- 100

![image](https://user-images.githubusercontent.com/6506666/113482160-9ecddd00-949d-11eb-84bd-9c5e02ebae52.png)

The max incoming/outgoing peers in the config.tom of the public sentry was set okay by kira. (think it was 1024 peers)

Something prevented to discover more peers. I did change the whitelist on the firewall but I would guess that wouldn't matter.

**If someone notices the same please comment below**

**Comment by denisanix** [comment]
same issue -- followed the approach above

before:
![Screenshot 2021-04-03 183248](https://user-images.githubusercontent.com/81810153/113483374-c035c580-94ab-11eb-8d73-f69cbd102cb4.jpg)


and after

![Screenshot 2021-04-03 183908](https://user-images.githubusercontent.com/81810153/113483413-efe4cd80-94ab-11eb-8747-b3261b19b3f9.jpg)

**Comment by asmodat** [comment]
thank you, resolved on branch `testnet-2`
